from . import ir_rule
from . import users
from . import res_config_settings
from . import res_company
from . import partner
from . import order_pickup_method
from . import account_move
from . import sale
from . import sale_agreement
from . import stock_location
from . import stock_picking
from . import stock_picking_type
from . import stock_move
from . import stock_move_line
from . import purchase_order
from . import stock_warehouse
from . import stock_interco_move_line
from . import stock_production_lot
from . import crm_team
from . import partner_pricelist
from . import product_pricelist
from . import product_category