# -*- coding: utf-8 -*-
from odoo import models, fields, api, SUPERUSER_ID, _
from odoo.exceptions import UserError,ValidationError

import logging
_logger = logging.getLogger(__name__)


class StockRule(models.Model):
	_inherit = 'stock.rule'


	def _register_selected_lot_interco_move_line(self, orders):
		for order in orders:
			# origin_interco_move_lines = order.picking_ids.mapped('interco_move_line_ids')
			# looping origin source picking from Customer Sale Order from source company
			for picking in order.origin_interco_order_id.picking_ids.filtered(lambda r:r.picking_type_id.code=='outgoing'):
				for move in picking.move_lines:

					origin_interco_move_line = picking.interco_move_line_ids.filtered(lambda r:r.product_id.id==move.product_id.id)
					new_data = origin_interco_move_line._convert_to_write({name: origin_interco_move_line[name] for name in origin_interco_move_line._cache})
					
					interco_move = order.picking_ids.filtered(lambda r:r.picking_type_id.code=='outgoing').mapped('move_lines').filtered(lambda r:r.product_id.id==move.product_id.id) # find same move on interco move from origin interco move

					assert len(interco_move)==1, "Found %s interco_move" % (len(interco_move))
					new_data.update(dict(picking_id=interco_move.picking.id, move_id=interco_move.id, warehouse_id=origin_interco_move_line.warehouse_id.id,  lot_id=origin_interco_move_line.lot_id.id, qty=origin_interco_move_line.qty, free_qty=origin_interco_move_line.free_qty))

					created_obj = self.env[origin_interco_move_line._name].create(new_data)
					



	@api.model
	def _run_pull(self, procurements):
		sale_line_ids = []
		for proc in procurements:
			# _logger.info(proc)
			for pp in proc:
				try:
					sale_line_ids.append(pp.values.get('sale_line_id'))
				except Exception as e:
					pass
		# if sale
		if len(sale_line_ids):
			sale_lines = self.env['sale.order.line'].browse(sale_line_ids)
			assert len(sale_lines)>0, "No Order Found on defined Sales Line Ids."
			# find all orders generated by intercompany rules.
			auto_generated_orders = sale_lines.mapped('order_id').filtered(lambda r:r.auto_generated==True)
			if len(auto_generated_orders):
				
				return super(StockRule, self.with_context(dict(auto_assign_origin_interco_move_line_ids=True)))._run_pull(procurements)
		return super()._run_pull(procurements)