from . import wizard_report_tax_07
from . import wizard_report_tax_08
from . import wizard_report_tax_09
from . import wizard_report_tax_10
from . import wizard_report_tax_11
from . import wizard_report_tax_18
from . import wizard_report_tax_01
from . import wizard_report_tax_02
from . import wizard_report_tax_03
from . import wizard_report_tax_04
from . import wizard_report_tax_05
from . import wizard_report_tax_06